aws:
  accessKey: ${key}
  secretKey: ${secret}
  bucket:
    name: bragin.pictures
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pictures
    username: ${user.db}
    password: ${pass.db}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    hibernate:
      ddl-auto: update